### ISSUE TITLE
BUFR2IODA: Add ObsError and PreQC group/variable with a constant value for marine insitu BUFR 

### ISSUE THREAD

**Issue by ShastriPaturi** [JCSDA-internal/ioda-converters#1050]
## Description
>Currently the bufr2ioda.x creates IODA-v2 netcdf file reading the mnemonics from marine insitu BUFR data. The marine insitu BUFR data does not have mnemonics for ObsError and PreQC.
>Add ObsError and PreQC group/variable with a constant value.

**Comment by rmclaren** [comment]
@ShastriPaturi Could you attach python code you use to append your globals to the netcdf files. I'd just like to see exactly how you do it.

**Comment by rmclaren** [comment]
@ShastriPaturi A copy of the text you get when you do ncdump -h on one of your fixed files would also be great :)

**Comment by ShastriPaturi** [comment]
The text from ncdump -h :
group: MetaData {
  variables:
        int64 dateTime(nlocs) ;
                dateTime:_FillValue = 99999997952LL ;
                string dateTime:long_name = "dateTime" ;
                string dateTime:units = "seconds since 1970-01-01T00:00:00Z" ;
        float depth(nlocs) ;
                depth:_FillValue = 1.e+11f ;
                string depth:long_name = "Depth below sea surface" ;
                string depth:units = "m" ;
        float latitude(nlocs) ;
                latitude:_FillValue = 1.e+11f ;
                string latitude:long_name = "Latitude" ;
                string latitude:units = "degrees_north" ;
                latitude:valid_range = -90.f, 90.f ;
        float longitude(nlocs) ;
                longitude:_FillValue = 1.e+11f ;
                string longitude:long_name = "Longitude" ;
                string longitude:units = "degrees_east" ;
                longitude:valid_range = -180.f, 180.f ;
  } // group MetaData
group: ObsValue {
  variables:
        float sea_water_temperature(nlocs) ;
                sea_water_temperature:_FillValue = 1.e+11f ;
                string sea_water_temperature:long_name = "Temperature at depth" ;
                string sea_water_temperature:units = "deg K" ;
                sea_water_temperature:valid_range = 250.f, 320.f ;
  } // group ObsValue

group: PreQC {
  variables:
        int sea_water_temperature(nlocs) ;
  } // group PreQC

group: ObsError {
  variables:
        float sea_water_temperature(nlocs) ;
  } // group ObsError
}

**Comment by ShastriPaturi** [comment]
The python script:
import numpy as np
import netCDF4 as nc

file='test1.nc'

dbuoyb=nc.Dataset(file,mode='r+', format='NETCDF4')
temp=dbuoyb.groups['ObsValue'].variables['sea_water_temperature'][:]
temp=temp-273.15
dbuoyb.groups['ObsValue'].variables['sea_water_temperature'][:] = temp

grp_PreQC         = dbuoyb.createGroup('PreQC')
var_PreQC_temp    = grp_PreQC.createVariable('sea_water_temperature', np.int32, ('Location'))
var_PreQC_temp[:] = 0.

grp_ObsError         = dbuoyb.createGroup('ObsError')
var_ObsError_temp    = grp_ObsError.createVariable('sea_water_temperature', np.float32, ('Location')) 
var_ObsError_temp[:] = 0.12 

dbuoyb.close()

print ("conversion complete")

**Comment by rmclaren** [comment]
@srherbener @emilyhcliu Shastri wants to have a way to add a variable column (sea_water_temperature **preqc** and **obserror** data in his example). We currently have a mechanism for adding global variables that look like this when you do `ncdump -h`:

```
// global attributes:
                string :_ioda_layout = "ObsGroup" ;
                :_ioda_layout_version = 0 ;
                :sensorCentralFrequency@MetaData = 89.f, 157.f, 183.311f, 183.311f, 190.311f ;
                string :platformCommonName@MetaData = "MHS" ;
```

The current mechanism allows you to specify **global** variables which are listed in their own sections. The variables are not listed in the variable groups (ex: MetaData). My question is if the current globals are useful or if they should be modified to work more like what Shastri wants (adding actual variables inside groups sized according to the number of locations (or whatever dimension makes sense). Or does it make more sense to have a concept of a derived variable. I'm asking because I don't have a very good understanding of how this data is used down the line...

**Comment by rmclaren** [comment]
@ShastriPaturi You can remove the lines:
```
temp=dbuoyb.groups['ObsValue'].variables['sea_water_temperature'][:]
temp=temp-273.15
dbuoyb.groups['ObsValue'].variables['sea_water_temperature'][:] = temp
```
by modifying your YAML file so that your exports::variables:: sea_water_temperature section reads like this:
```yaml
          sea_water_temperature:
            query: "<sea temperature query>"
            transforms:
              - offset: -273.15
```

**Comment by ShastriPaturi** [comment]
Thanks @rmclaren

**Comment by ShastriPaturi** [comment]
> @srherbener @emilyhcliu Shastri wants to have a way to add a variable column (sea_water_temperature **preqc** and **obserror** data in his example). We currently have a mechanism for adding global variables that look like this when you do `ncdump -h`:
> 
> ```
> // global attributes:
>                 string :_ioda_layout = "ObsGroup" ;
>                 :_ioda_layout_version = 0 ;
>                 :sensorCentralFrequency@MetaData = 89.f, 157.f, 183.311f, 183.311f, 190.311f ;
>                 string :platformCommonName@MetaData = "MHS" ;
> ```
> 
> The current mechanism allows you to specify **global** variables which are listed in their own sections. The variables are not listed in the variable groups (ex: MetaData See Shastris example above). My question is if the current globals are useful or if they should be modified to work more like what Shastri wants (adding actual variables inside groups sized according to the number of locations (or whatever dimension makes sense). Or does it make more sense to have a concept of a derived variable. I'm asking because I don't have a very good understanding of how this data is used down the line...

@srherbener @emilyhcliu and @rmclaren the marine BUFR data does not have any mnemonics corresponding to ObsError and PreQC. In the example I have included, I add these variables separately through a simple python script, which I want to avoid.

**Comment by srherbener** [comment]
Sorry about the slow response - getting caught up in tasks for the upcoming release on Oct 7.

Let me see if I understand the request.

@ShastriPaturi you have created a YAML file for @rmclaren's bufr reader/converter that gets you to a ioda file that is good but it is still missing two variables that you want: PreQC/sea_water_temperature and ObsError/sea_water_temperature. The reason these are missing is that there are no corresponding data in the input bufr file so you would like to have a way for the converter to create these variables with default values. (You've written a separate python script to do this last part, but you would like @rmclaren's converter to do it instead.) Is this correct?

I'm not clear on what the current mechanism for a global variable is. It looks like you can specify a variable name with values and place these in the file's global attributes list (which is quite different that creating a variable). Is this correct? And if so, I'm not sure this is a good approach since nlocs could be huge.

I think providing a way for the converter to create the PreQC and ObsError versions of ObsValue variables, filled with default values, would be quite useful. This would produce a file with the structure @ShastriPaturi shows in his sample `ncump -h` output. I think it is often the case where the data provider (input BUFR file) does not include QC marks (PreQC) or error estimates (ObsError) so it would be nice to be able to fill these in with default values. Does this sound like what is desired, and is feasible to do?

**Comment by ShastriPaturi** [comment]
Thanks @sherbener. The 3rd paragraph is what is intended.Sent from my iPhoneOn Sep 27, 2022, at 4:36 PM, Stephen Herbener ***@***.***> wrote:﻿
Sorry about the slow response - getting caught up in tasks for the upcoming release on Oct 7.
Let me see if I understand the request.
@ShastriPaturi you have created a YAML file for @rmclaren's bufr reader/converter that gets you to a ioda file that is good but it is still missing two variables that you want: PreQC/sea_water_temperature and ObsError/sea_water_temperature. The reason these are missing is that there are no corresponding data in the input bufr file so you would like to have a way for the converter to create these variables with default values. (You've written a separate python script to do this last part, but you would like @rmclaren's converter to do it instead.) Is this correct?
I'm not clear on what the current mechanism for a global variable is. It looks like you can specify a variable name with values and place these in the file's global attributes list (which is quite different that creating a variable). Is this correct? And if so, I'm not sure this is a good approach since nlocs could be huge.
I think providing a way for the converter to create the PreQC and ObsError versions of ObsValue variables, filled with default values, would be quite useful. This would produce a file with the structure @ShastriPaturi shows in his sample ncump -h output. I think it is often the case where the data provider (input BUFR file) does not include QC marks (PreQC) or error estimates (ObsError) so it would be nice to be able to fill these in with default values. Does this sound like what is desired, and is feasible to do?

**Comment by gthompsnJCSDA** [comment]
In my own opinion, there is NO need to give/assign values of PreQC and ObsError in a converter - unless something is known a priori about those data.  This is really the realm of UFO.  You can easily pick from a bunch of methods to assign the ObsError to a variable - there are many example YAMLs for this.  The PreQC value is completely a design of EMC and not really relevant if one proposes to set some constant for the entire dataset.  UFO creates the final variable ```EffectiveQC``` that is the outcome of all filters applied to the incoming data.  ```PreQC``` is basically created by the ObsProc (observation processing) group at EMC to put into the variable called ```QualityMark``` in prepBUFR and GSI.

Therefore, I suggest this issue be closed and resolve it directly with actions in UFO since the data quality control is supposed to occur there anyway.

**Comment by rmclaren** [comment]
@srherbener I think you understand things very well :) The current mechanism for adding globals adds the following section to the netcdf files:

```
// global attributes:
                string :_ioda_layout = "ObsGroup" ;
                :_ioda_layout_version = 0 ;
                :sensorCentralFrequency@MetaData = 89.f, 157.f, 183.311f, 183.311f, 190.311f ;
                string :platformCommonName@MetaData = "MHS" ;
```

I would have thought that UFO could make use of this data in some way.. especially for instances where you have a constant value that applies to each location of the data.

@gthompsnJCSDA @srherbener Thanks so much for your feedback as I really don't understand UFO and its capabilities very well. Do the globals in their current form provide a benefit (are they useful) or would it be better to remove them (simplifying the YAML and code)? Thanks again for providing your opinions about this matter. At some point we should all get together and talk about how we want this feature (BUFR ingestion) to evolve in the long run.

**Comment by srherbener** [comment]
@gthompsnJCSDA thanks for your feedback. I agree that since UFO can already handle missing PreQC and ObsError data, then that is a much better place to resolve this than in a ioda converter.

I agree with @gthompsnJCSDA's recommendation to leave the converter as is and use UFO features to resolve this issue.

**Comment by srherbener** [comment]
@rmclaren I think the global attributes feature of the ioda (hdf5) data model is useful. I think it would help with clarity to call the feature in the bufr converter "global attribute" instead of "global variable" and have the global attribute feature be just a general (name, value) pair for specification in the YAML. Something like:
```
...
   global attribtues:
     - name: platformCommonName
        value: "MHS"
     - name: sensorCentralFrequency
        value: [ 89.f, 157.f, 183.311f, 183.311f, 190.311f ]
...
```

The ioda engines attributes support defining a shape for an attribute which allows for vectors and arrays of data in the attribute value.

**Comment by rmclaren** [comment]
@srherbener No type? When I create the global attributes I use code that looks like this:

```cpp
template<typename U = void>
void _addTo(ioda::Group& group,
            typename std::enable_if<is_vector<T>::value, U>::type* = nullptr)
{
    ioda::Attribute attr = group.atts.create<typename T::value_type>(name, \
                           {static_cast<int>(value.size())});
    attr.write<typename T::value_type>(value);
}
```

Where the function exists inside a template class GlobalDescription<T> where the type T is determined from the "type" field the user specifies in the YAML file.

**Comment by srherbener** [comment]
@rmclaren sorry, you will need a type specification in the YAML along with the name and value specs.

I'm not aware of eckit::Configuration being able to infer data types, so I think the idea would be, as you say, to read in the type spec and use that to set the type for reading the value spec out of the YAML file as well as what to use for the templated _addTo function call.

**Comment by travissluka** [comment]
@ShastriPaturi @guillaumevernieres as a follow up to our conversation this morning, with regard to this issue:
I agree that we should not need to add `ObsError` and `PreQc` during the ioda converter step if they do not exist. We can simply set those at runtime in the UFO yaml file. 

To test, I removed `ObsError` and `PreQc` from the ADT obs used by the soca ctest, and added the following filter:
```
  - filter: Perform Action
    action:
      name: assign error
      error parameter: 0.1
```
and the 3dvar worked fine and produced the same answers. `PreQc` is not needed unless you specifically have a filter that uses it, so it's just a matter of making sure we assign an error at runtime

**Comment by ShastriPaturi** [comment]
> @ShastriPaturi @guillaumevernieres as a follow up to our conversation this morning, with regard to this issue: I agree that we should not need to add `ObsError` and `PreQc` during the ioda converter step if they do not exist. We can simply set those at runtime in the UFO yaml file.
> 
> To test, I removed `ObsError` and `PreQc` from the ADT obs used by the soca ctest, and added the following filter:
> 
> ```
>   - filter: Perform Action
>     action:
>       name: assign error
>       error parameter: 0.1
> ```
> 
> and the 3dvar worked fine and produced the same answers. `PreQc` is not needed unless you specifically have a filter that uses it, so it's just a matter of making sure we assign an error at runtime

Thanks @travissluka thank you.
Will try and let you know.

**Comment by ShastriPaturi** [comment]
@travissluka, adding the filter to obs yaml file as you suggested passes the 3dvar but I had to use the nco command ncrename to rename the dimensions from "Location" to "nlocs".
The IODA bufr file does have "Location" instead of "nlocs" as dimensions. @rmclaren is there a way to rename them in the yaml file?

**Comment by rmclaren** [comment]
@ShastriPaturi No there is not. We used to call the "Location" variable "nlocs" but the decision was made to standardize on the term "Location". So the primary index will be known as "Location" going forward.

**Comment by ShastriPaturi** [comment]
Thanks @rmclaren.

**Comment by ShastriPaturi** [comment]
"The only solution we could adopt in the interim is to change back those two dimension names back to nlocs and nchans and get it back into the develop branch."
This will be helpful.

**Comment by gthompsnJCSDA** [comment]
I am going to close out this issue, because the focus has shifted entirely.  Another one could be opened that simply tries to change the ```Location``` variable back to ```nlocs``` which also requires updating a rather massive number of ```testoutput``` reference files.  The effort to change the code and reference files _may not be worth it_ if we can adopt the **JEDI Data Conventions** soon enough, otherwise a set of corresponding changes will have to revert back them back.  A difficult decision on which route to take!
