### ISSUE TITLE
hdf5 converter for ATMS convert to epoch

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#1099]
The python ioda converter for ATMS data currently uses a string datetime object.   This should be updated to a new datetime that contains the number of seconds elapsed since a reference epoch, currently set to 1970-01-01T00:00:00Z.

**Comment by climbfuji** [comment]
@BenjaminRuston For my curiosity, is the atms converter the only one still using string datetime objects? I am asking because I see these skylab crashes on systems using spack-stack when atms observations are included. If I exclude atms observations but leave all other obs types in place, the experiments run fine.

**Comment by BenjaminRuston** [comment]
@climbfuji likely not the only one, so this is why EricL modification is so key can reuse the `get_epoch_time` for the other converters
