### ISSUE TITLE
Add releaseTime to NCEP ADPUPA converter

### ISSUE THREAD

**Issue by haydenlj** [JCSDA-internal/ioda-converters#1322]
## Description
The variable releaseTime is required by Skylab, however, IODA files produced by the NCEP ADPUPA converter do not contain this information. The variable should be added to the converter output

## Requirements

Determine release time from the prepbufr data

## Acceptance Criteria (Definition of Done)
code outputs ioda file with the release time included and the file is accepted by Skylab

## Dependencies
none

**Comment by haydenlj** [comment]
@emilyhcliu @PraveenKumar-NOAA @gthompsnJCSDA @rmclaren 
How can the release time be determined in the prepburf files? The code in `bufr_ncep_prepbufr_adpupa.py` seems to be expecting a 2 dimensional array (e.g. line 110 `num_locs = lat.shape[0]`), however, when I print the shape, the array is 1 dimensional. Is there a way to determine where each profile starts so that we can take the time at that point as the release time?

**Comment by rmclaren** [comment]
The reason that you get 1 dimensional arrays here is because of the group_by fields specified in the call to the getter
`r.get('latitude', 'prepbufrDataLevelCategory')`.  If you want to see the original shape you could do `r.get('latitude').shape`. 

It might be that you might not want to apply group_by fields to anything, as this will have the effect of flattening the arrays (Remove/rotate away the PRSLEVEL dimension). So you could just leave out the second argument from the `r.get('example')` calls. In this case each "row" in the resulting data set will correlate to a specific PRSLEVEL.  It all depends on what you want to do with the data....

**Comment by PraveenKumar-NOAA** [comment]
@haydenlj @huishao-r  I am working on adding this to the ADPUPA BUFR Python API (https://github.com/JCSDA-internal/ioda-converters/issues/1298#event-9843424585, https://github.com/NOAA-EMC/JEDI-T2O/issues/78), but releaseTime/receiptTime can't be added to the existing YAML converter as it belongs to a different branch which does not follow group_by variable path.
