### ISSUE TITLE
[Bug] bufr2ioda.x Crash When Requesting a Non-Existent Query for SATWND Conversion

### ISSUE THREAD

**Issue by spanNOAA** [JCSDA-internal/ioda-converters#1427]
## Current behavior (describe the bug)
The program usually issues a warning message for a non-existing query and then moves on to the next one. But in the case of SATWND, it unexpectedly leads to a segmentation fault when requesting a non-existing query.

## To Reproduce

> What computer are you running on?
Hera
> What compilers/modules are you using?
spack-stack-1.5.0
> Steps to reproduce the behavior

I have two examples to request non-existing queries for AIRCFT and SATWND.
Both of them are on Hera: /scratch2/BMC/wrfruc/Sijie.Pan/iodaconv/SATWND_issue

## Expected behavior

When running the "bufr2ioda.x bufr_ncep_prepbufr_aircft.yaml" command, numerous warning messages appear indicating non-existent queries. 
Conversely, executing "bufr2ioda.x bufr_ncep_prepbufr_satwnd.yaml" results in an immediate "Segmentation fault."

**Comment by rmclaren** [comment]
The query `*/PRSLEVEL/Z___INFO/Z__EVENT/ZOB` should be `*/Z___INFO/Z__EVENT/ZOB` as PRSLEVEL is not a repeatable sequence (see the output for print_queries.x)... I know this is confusing as PRSLEVEL is usually present for the other data types in this file... So that will solve the issue, but I still need to look at why its crashing instead of giving a warning.

**Comment by rmclaren** [comment]
Fixed in pull request

**Comment by PatNichols** [comment]
@spanNOAA Can we close this one now?

**Comment by spanNOAA** [comment]
Yes. Thanks!

Sijie
