### ISSUE TITLE
bufr2ioda based adpupa converter correct metadata

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#1457]
## Description

the `pressure` variable should be stored in `MetaData` for radiosonde:
```
range(/ObsValue/pressure): [300, 109900]
```

## Acceptance Criteria (Definition of Done)
correct location of `pressure` variable
confirm resulting IODA file works with downstream data trials

**Comment by PraveenKumar-NOAA** [comment]
@BenjaminRuston pressure variable is stored already in MetaData for radiosonde (adpupa prepbufr). 

group: MetaData {
  variables:
  	int64 dateTime(Location) ;
  		dateTime:_FillValue = 9223372036854775807LL ;
  		string dateTime:long_name = "Datetime" ;
  		string dateTime:units = "seconds since 1970-01-01T00:00:00Z" ;
  		string dateTime:coordinates = "longitude latitude" ;
  	float height(Location) ;
  		height:_FillValue = 3.402823e+38f ;
  		string height:long_name = "Height of Observation" ;
  		string height:units = "m" ;
  		string height:coordinates = "longitude latitude" ;
  	float latitude(Location) ;
  		latitude:_FillValue = 3.402823e+38f ;
  		string latitude:long_name = "Latitude" ;
  		string latitude:units = "degrees_north" ;
  		string latitude:coordinates = "longitude latitude" ;
  		latitude:valid_range = -90.f, 90.f ;
  	float longitude(Location) ;
  		longitude:_FillValue = 3.402823e+38f ;
  		string longitude:long_name = "Longitude" ;
  		string longitude:units = "degrees_east" ;
  		string longitude:coordinates = "longitude latitude" ;
  		longitude:valid_range = 0.f, 360.f ;
  	float pressure(Location) ;
  		pressure:_FillValue = 3.402823e+38f ;
  		string pressure:long_name = "Pressure" ;
  		string pressure:units = "Pa" ;
  		string pressure:coordinates = "longitude latitude" ;

What else I should do?

**Comment by PraveenKumar-NOAA** [comment]
@BenjaminRuston I think I need to update this for adpupa bufr.

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA on this PR that was merged the `pressure` is stored under `ObsValue`:
https://github.com/JCSDA-internal/ioda-converters/pull/1454

in this PR that is in progress it is correctly stored under `MetaData`:
https://github.com/JCSDA-internal/ioda-converters/pull/1453

**Comment by PraveenKumar-NOAA** [comment]
@BenjaminRuston pressue is MetaData, I will create an issue and fix this in #1454. But why tests are failing in #1453. I will fix #1453?

**Comment by BenjaminRuston** [comment]
great thanks @PraveenKumar-NOAA ,, the fix for PR1454 can be linked to this issue:
https://github.com/JCSDA-internal/ioda-converters/issues/1457

and yes please keep digging on PR1453, again I did a conflict resolution please look over that commit I did, thought it was correct but could use another set of eyes
