### ISSUE TITLE
Missing value threshold is specific to NetcdfIO, hidden, and not required

### ISSUE THREAD

**Issue by svahl991** [JCSDA-internal/ioda-converters#154]
Right now the NetcdfIO code has a threshold (1e+8), above which any value is treated as a missing value. There's not a problem with this, except that I've noticed people writing their ioda-converters with this functionality in mind. So if their converter notices a missing value, they just populate a value larger than 1e+08 and trust that it will be treated appropriately inside IODA.

The issue is that this functionality and value are not required by other classes that inherit from the IODAIO abstract class. So there's a potential that another I/O class would not include this functionality at all, or might choose a different threshold value. This could cause bugs later, especially when the converters start using a python wrapper around IODAIO to write their IODA data files, so they might not be writing netCDF files at all.

Also, because this value is somewhat hidden in the NetcdfIO source code (not even in a public header file), I've noticed that people aren't exactly sure what the threshold value is when they're writing their converters.

**Comment by srherbener** [comment]
JEDI has its own predefined numbers that represent missing values. There is one value for each data type (integer, float, double, etc.) that represents "missing".

The idea in IodaIO is to convert missing values between those in the file (however they are represented) and those in memory (JEDI missing values). We started with just using large numbers to represent missing values in the files (quick and dirty), so that we could accommodate ODB and netcdf files, and 1e+8 was chosen as a threshold so that integers, floats and doubles could all use it.

The threshold scheme isn't ideal because it allows a lot of different values to represent "missing" and we would rather have just one value per data type as used in the JEDI scheme. Netcdf has a method for representing missing values of which they call "fill values". You can specify any value to be a fill value, and you can do this on a variable-by-variable basis. Netcdf provides default fill values for each data type which happen to be large values (that are typically not encountered in atmospheric/oceanic obs data). These seem like good values to use for netcdf so the plan is to change NetcdfIO reader to recognize the netcdf default fill values and replace these with JEDI missing values. This will allow us to get rid of the 1e+8 threshold value (and scheme).

We will need to get the netcdf default fill values into the obs files that the converters are writing. The NetcdfIO writer already converts JEDI missing values to the netcdf default fill values, so we should pick this up automatically when we switch NcWriter to use the IodaIO interface.

It seems that ECMWF or the Met Office would already have missing value schemes in place for ODB files. If so, we can use those schemes in our IodaIO interface.

**Comment by svahl991** [comment]
Thanks for this, Steve. If I'm understanding correctly, this means that when NcWriter starts using the IodaIO interface, then converters that are currently populating an arbitrary value larger than 1+e8 to represent a missing value will need to start populating the specific JEDI missing values instead? Is there a way for them to retrieve these numbers? I don't think we want the converters populating the netcdf fill values because the converter shouldn't know that a netCDF file is getting written behind IodaIO.

If this is all wrong and I'm still confused, I apologize, and maybe we'll need to talk face to face about it sometime.

**Comment by srherbener** [comment]
Yes you understand correctly, and part of the IodaIO interface will be methods to provide the missing values that go into the dictionary values (so that the IodaIO writer will put netcdf fill values, or the ODB scheme's missing values, into the output files).

**Comment by srherbener** [comment]
I believe this issue is resolved now.

The NetcdfIO subclass on IodaIO class now checks each variable for an _FillValue attribute. If it exists the code uses the  value in the attribute to identify missing values, and if it doesn't exist it uses the netcdf default fill value to identify missing values.

The OdcIO subclass does the same thing for an ODB file using the ODC API to get the missing data values.

The use of a the 1e+8 threshold is long gone.

Given this, is it okay to close this issue?
