### ISSUE TITLE
TROPICS converters allow graceful exit on no data

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#1580]
## Description

when the TROPICS data file contains no data have the converter gracefully exit printing a WARNING but no data file

## Acceptance Criteria (Definition of Done)
converter does a graceful exit

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the get_data_from_files function to check if the file contains data. If the file is empty, it prints a WARNING message and returns None, which leads to a graceful exit in the main function.

You can review changes in this commit: https://github.com/lattaai13/JCSDA-internal-ioda-converters-1580/commit/f930f976aece05118e1e3d971c3a8f2b0eb98b03.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
