### ISSUE TITLE
SNODAS snow observations to IODA format

### ISSUE THREAD

**Issue by jmccreight** [JCSDA-internal/ioda-converters#206]
This is a longer term goal (maybe not an epic?) to build this converter generally.

The main complication at the start is that the inputs are a bit of a moving target. The SNODAS observations are currently compiled by that (SNODAS) operational system, but we want to make them available through IODA.

There may be several different incarnations of this converter over time, or it may need to take different inputs or configurations. To start, I have a pickle file that represents the input data and it can be unpickled.

**Comment by jmccreight** [comment]
Dear @travissluka and @srherbener, I would be grateful for a bit of advice on how best to model this new coverter. I've been looking at `src/` a bit and I sort of randomly (though not entirely) settled on copying the approach on the code in `src/marine/gds2_sst2ioda.py.in`

Before I go too far in that direction, I figured I should ask if that's a good choice or if you would point me to a different converter for modeling the new one. The conversion in there seems to fit my data well, so my question is more about best practices on the ioda-converters side. 

TIA

**Comment by srherbener** [comment]
Hi @jmccreight, not only having the inputs be a moving target, we are also in transition with the converters. Currently, they use a Python stand-alone class called NcWriter and we want that class to eventually use the writer built into IODA. Also, the performance of the Python scripts is of concern for operational use and we will likely be pulling more functionality into compiled executables.

I would say the best thing to do is get something simple in place now that involves minimal effort, and make incremental changes as needed as the SNODAS inputs and converters evolve (ie, agile methodology). 

I think it would be good to use the `gds2_sst2ioda.py.in` script as a model since you feel it fits well with your data. Also, this script takes the approach of skipping the ExtractObsData step (intended for conventional data) which helps with streamlining your flow.

One thing is that we decided to use the COARDS convention (https://ferret.pmel.noaa.gov/Ferret/documentation/coards-netcdf-conventions)  for units which means that each variable in the output netcdf file needs an associated metadata called "units" which denotes the units of the values in the variable. The GSI scripts have been recently updated with this feature, but the marine scripts haven't added this. You might want to take a look at the GSI scripts, or ask @CoryMartin-NOAA for some help with this.

**Comment by jmccreight** [comment]
It's functional... 
https://github.com/JCSDA/ioda-converters/tree/feature/snodas
I just realized that I did not include any data yet. So there's a bit of a vacuum. Need to pare the data and write a test for it still. But we can discuss the inner workings.

**Comment by srherbener** [comment]
@jmccreight, sounds great. I think the next step would be to submit a pull request and request two or three of us to review. You might want to do the steps you noted (pare the data, add a test) before submitting the pull request.

One thing I noticed is that it looks like you need to merge the current develop branch into your feature/snodas branch. You can do this by the following:
~~~~~~~~
git remote update -p
git checkout develop
git pull
git checkout feature/snodas
git merge develop
~~~~~~~~

It's a good practice to merge in the current develop branch periodically so you stay up-to-date with others' changes (and potentially catch issues earlier rather than later).

Thanks!

**Comment by jmccreight** [comment]
[This commit](https://github.com/JCSDA/ioda-converters/commit/3108b0e7c6f2153a2e0cd3ae091739447e598df5) represents a MVP 
1. it's tested
2. it does the basic conversion

Next: 
1) There are lots of TODOs in the main script for potentially desired functionality. 
2) Scope the IODA format requirements/conventions/best practices (as mentioned above) and ensure compliance good faith.

**Comment by srherbener** [comment]
@jmccreight, do you anticipate this getting completed in either April 2020 or May 2020. If so, please add the corresponding Milestone (OBS - April 2020, OBS - May 2020). Thanks!

**Comment by jmccreight** [comment]
@amfox37 ☝️

**Comment by mmiesch** [comment]
@jmccreight @amfox37 - what is the status of this?  We're cleaning up the ZenHub boards for the new AOP.  Can we close this and then create a more up-to-date follow-up issue on the remaining work that needs to be done?

**Comment by amfox37** [comment]
First version that we work with was done, but never finalized and merged. Let's close this, and the work will be finalized in collaboration with OWP colleagues in LAND2.3 AOP21#156
