### ISSUE TITLE
ioda data structure for hyperspectral IR sounder radiance

### ISSUE THREAD

**Issue by weihanucar** [JCSDA-internal/ioda-converters#253]
@srherbener @emilyhcliu 
Currently, each channel has a separate variable for the radiance input netcdf file.
For  hyperspectral IR sounder radiance, there are 1000 to 16000 channels which could be a challenge to the current IODA netcdf data format.
I think it is worth having a conversation about how best to accommodate hyperspectral IR sounders with thousands of channels, and also other radiance data.

The cris ioda variables are list in the attached file:

[cris-fsr_npp_obs_2018041500_m_variable.txt](https://github.com/JCSDA/ioda-converters/files/4289004/cris-fsr_npp_obs_2018041500_m_variable.txt)

**Comment by srherbener** [comment]
@weihanucar and @emilyhcliu, I agree that having a separate variable for each channel is not a good implementation. We did it that way simply because there was not a way to accommodate  one variable with many channels in the initial IODA implementation. I am currently upgrading the IODA implementation to be able to handle mulit-dimensioned (more dimensions other than nlocs) data. Once that is done we can change the file format accordingly.
