### ISSUE TITLE
BufrConverter: Both nlocs and nchans are defined with unlimited size.

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#372]
For some reason the dimensions for the NetCDF files created are reported to have UNLIMITED size. According to @srherbener these sizes should be fixed.

**Comment by srherbener** [comment]
The unlimited size is coming from this line:

https://github.com/JCSDA-internal/ioda-converters/blob/1ed4019613a611deea243f36cdb4392df45232a9/src/bufr/IodaEncoder/IodaEncoder.cpp#L62

This argument to the NewDimensionScale constructor is setting the maximum allowed dimension size. 

It's best to set dimensions to fixed sizes if you know those sizes beforehand. I'm not sure if it's possible to know nlocs before reading the bufr file, but hopefully you can determine the other dimension sizes.

- Best case is all dimensions be fixed sizes. Best performance.
- Next best case is nlocs is unlimited and all other dimensions are fixed. ObsStore backend can handle this already.
- Next is multiple dimensions are unlimited. ObsSpace backend can't handle this yet, so more development is necessary to support this.

**Comment by rmclaren** [comment]
@srherbener 

I can determine the number of locations ahead of time very easily, but I had some additional questions:

1) Should chunk sizes for dimension variables be defaulted to a value like (ex: 1000) or just be the length of that dimension (ex: nlocs)?

2) Should the user be able to specify a chunksize for a dimension variable manually through the configuration or by adding an optional "chunkSize" parameter to the dimension description?

**Comment by srherbener** [comment]
@rmclaren sorry about the slow response on this. It dropped through the cracks.

1. The HDF5 developers recommend keeping the chunk size <= 1 MB. The chunk size determines how much space is allocated so ideally you want the chunk size to be a factor of the total size. If the total size is 20, then chunk sizes of 4, 5, 10 are good because the memory gets utilized at a 100%. If you were to select a chunk size of 7, you waste one location at the end, ie three chunks, where the usage is 7, 7, and 6 (20 items in a space big enough for 21 items). If the chunk size is 9, then there is a lot of waste: 3 chunks holding 9, 9 and 2 items (8 unused spaces).

2. Having the user specify chunk sizes might be a good feature but only for the sophisticated user. It might be a bit much to ask users in general to be up to speed on hdf5 chunking. If you decide to add this, it would probably be good to make it optional and thus hidden by default.
