### ISSUE TITLE
[Bug]  Parsing the CHNM mnemonic from original BUFR to convert to IODA netCDF4 files appears to offset the channel list

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#491]
## Current behavior (describe the bug)

bufr2ioda for MHS (and 3 other satellite platforms) appears to offset the list of channel numbers from what I expect to see when capturing the channel number direct from the BUFR messages.  Example is that channels 1-5 are requested for the brightness temperatures, but when capturing the CHNM mnemonic direct from buffer the list of channels appears as: 2, 3, 4, 5, 1E+11 when using ncdump after the conversion/output into IODA netcdf4 file. 

## To Reproduce

Using this file:  `iodaconv/test/testinput/bufr_mhs_new_format.yaml` from **feature/bufr2ioda_radiance_yaml_newNamingConvention** and running bufr2ioda.x produces an output file in the testrun subdirectory that can be queried with ncdump -v channelNumber\@MetaData.

## Expected behavior

I believe the list of channels should simply be 1 to 6.  This same (incorrect) behavior happens using AMSU-A, ATMS, and SSMIS input BUFR files as well.

**Comment by rmclaren** [comment]
So it turns out you have to be extremely careful when using ufbrep on NCEPLIB-bufr. The order in which you list parameters matters. So when you look at the table and the relative ordering between 2 elements is CHMN then TMBR (as an example) they must be listed that way otherwise there will be weird side effects... uuuuuuuuuuuuuuuuuuuuuggggggggggggggggg. So we can fix the immediate problem by listing the variables as follows [CHNM, TMBR] instead of the other way around. We need to check the other variables as well.

I could implement a work around where I query each mnemonic seperatly in a loop, but at this point I think it would be better to spend the time moving away from this API altogether as it is a minefield...

**Comment by rmclaren** [comment]
You should double check other lists of mnemonics and make sure that the ordering of the mnemonics is the same as they appear in the tables.

**Comment by BenjaminRuston** [comment]
@rmclaren and @gthompsnJCSDA closing this one as well as I think this was fixed
