### ISSUE TITLE
OBS3.2.3.1: Enhanced support for a wide variety of BUFR data (goal is any data in any BUFR file).

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA-internal/ioda-converters#550]
The purpose of this EPIC is to support a very wide variety of BUFR files (and hopefully PREPBUFR as well) for the purpose of YAML file based BUFR data ingestion to IODA (ultimately). 

Unfortunately the existing interface to BUFR files isn't very well suited for this so a major part of this effort is to extend the NCEPLIB-bufr library with an interface to make automatic reading of this data possible... I'm attempting to do this in such a way that the extension will be generally useful to anyone who needs to read BUFR data. I'm not at all clear whether this approach was a good idea, or not (it will remain to be seen).

Once the NCEPLIB-bufr extension is done the BUFR-Converter code will need to be updated to make full use of the new interface.

**Comment by rmclaren** [comment]
- NCEPLIB-bufr (feature/query)
  - Basic extension is working with ability to support most types of data including:
  - Trivial fields.
  - Sequences (both the fixed and delayed varieties).
  - Sequences can be arbitrarily nested within each other.
  - "for" field on getter functions can be used to associate values at different levels in the heirarchy
  - CCITT IA5 fields (anywhere in the data). Retrievable via get_as_chars (instead of just get) function on the ResultSet.
  - Retrieval of listing of all possible queries using modq_table module.
- Things I need to add (at least that I can think of right now):
  - Enhanced user readable printing of queries so you don't have to refer to the BUFR tables at all.
  - Lots of unit tests (not sure how far Nick and Praveen are getting).
  - Lots of doc strings
- Things not supported yet (possibly defer)
  - 3D fields found in PREPBUFR files (need to investigate)
  - Associated fields (seem to be very rare at NCEP, I've never seen an actual example of one in our data).
  - Python interface.

Ioda Converter/Bufr Converter (feature/query)
- Updated so that it uses the new interface in the NCEPLIB-bufr library.
  - YAML file now used query strings and no longer have a mnemonicSets section.
  - Basic retrieval of data works (repeated sequences of all kinds should basically work).
- What I'm working on. **
  - Working on adding support for CCITT IA5 character fields.
  - Updating existing features to be useful in the new non-mnemonic paradigm and be compatible with CCITT IA5 fields.
- Things I need to do after the stuff I'm working on.
  - Support for the "for" fields so you can make datasets that make sense in the light of repeated sequences (not hard as most of the leg work is done).

**Comment by rmclaren** [comment]
See the following spreadsheet for progress toward completion. Join in if you feel like it :)

https://docs.google.com/spreadsheets/d/1D68rWHCvuv3dOpZUGAGMqDdHqQD6c9VexMnJRf_QoXU/edit#gid=0
