### ISSUE TITLE
ioda-converter development for IMSfSCA FV3-tile files

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#584]
## Description
> In support of PSL scientists for land DA activity. The snow cover and snow water equivalent data are calculated from 4km IMS snow cover for C96, C128, .... grid system and output FV3-tile files. The ioda-converter was requested by them to convert the these FV3-tile files to ioda NetCDF format .

>What problem needs to be fixed?

Should we read six tile file together and output one netcdf file with ioda format or should we read one tile file each time and finally output six files with ioda format?

## Requirements

ctest will pass

## Acceptance Criteria (Definition of Done)
The users will use for their tests.

## Dependencies
No

**Comment by aerorahul** [comment]
@YoulongXia-NOAA 
I see 2 approaches:
1. combine the (observed) gridded data and the fv3 tiles (containing grid information; lat, lon) into a single file so that the resulting file contains the gridded data and the coordinates.  This file can then be the single input to the converter.
2. provide the converter 2 sets of files; gridded data and coordinate data and map the `i.j` of the gridded data to the `lon, lat` from the grid files.

Since this is a standalone converter for this type of data, I personally would go for option 2.

**Comment by YoulongXia-NOAA** [comment]
Data samples are  in https://github.com/ClaraDraper-NOAA/IMSobsproc/tree/feature/fIMS_modified/test/output for C96.

**Comment by YoulongXia-NOAA** [comment]
Dear all,

I am having a request from PSL scientists who worked for Land DA (snow). I initiated a discussion for such an issue. My idea is to read all six data files each time and all six files for grid lat-lon from /scratch1/NCEPDEV/global/glopara/fix/fix_fv3_gmted2010/C96/C96_oro_data to convert them into ioda format output using python code. Certainly we can read each tile data and then output an output file. If so, we will output six files for all six tiles. This may take too much space. If you have any suggetsions or comments, please input. Your suggestions are always welcome.

**Comment by CoryMartin-NOAA** [comment]
How is it too much space? It would be 96*96*6 observations, ~60,000, which is not a lot. I do think this is impractical to include C96 oro data, etc as a test file, so perhaps this converter might not have a test in the ioda-converters repo? (or maybe C6 for a test?)

**Comment by ClaraDraper-NOAA** [comment]
For the snow DA, we've been using C48 to test. It'd be great if we could match that. 

Also, there's a lot of no-data values in the files (southern hemisphere, and non-land), so we can reduce the file size by removing that (perhaps in my pre-processing code, rather than in the converter?).  

I suspect Rahul's first option above will be easiest - the pre-processing code doesn't currently read in the grid info (since it gets it indirectly through the index files), but it'd be easy enough to add it.

**Comment by aerorahul** [comment]
@ClaraDraper-NOAA 
I was going to ask re. option 1.  Would it be possible to store the lat, lon pair associated with the "observed" variable in the file itself during preprocessing (in your code) rather the converter?
If so, that would be splendid!

**Comment by YoulongXia-NOAA** [comment]
Let me search for and see if we can find C6 from FV3-bundle. However, if I do this test, I need PSL scientists to help to produce data for C6. Right now I can use C96 or C128 for python code development.  When I need a ctest, I will contact Clara or Tsega.

**Comment by YoulongXia-NOAA** [comment]
C6 data do indeed exist in FV3-bundle. For ctest, this may be an option.

**Comment by ClaraDraper-NOAA** [comment]
@aerorahul Yes, that would be possible. I'm on leave all next week though, and won't get to it this week.

Should I also look into discarding the nodata values ? (in which case I'd change the output to be a vector, rather than current grid).

**Comment by YoulongXia-NOAA** [comment]
This is a great discussion. After we have a decision, I will start to work with that direction.

**Comment by aerorahul** [comment]
I think having only the observation data (along with the coordinates) in a vector with the no-data values removed as the output of the processing would greatly simplify the IODA converter.
Thanks @ClaraDraper-NOAA

**Comment by ClaraDraper-NOAA** [comment]
Sounds good. There's a small chance I'll get to it tomorrow, otherwise I'll change it when I'm back from leave (unless @YoulongXia-NOAA  is feeling impatient and wants to do it).

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA I am patient and I can wait for your sample data as I have other tasks to work.  I am afraid I will handle it improperly as I do not know your code very well.  No rush and pressure to you at all.

**Comment by YoulongXia-NOAA** [comment]
@tsga @ClaraDraper-NOAA, the today's meeting with Mike and he brought a related question: if you calculate snow cover fraction from 4km data for a given irregular FV3-grid, some IMS grid points may be used one more times when worked as a regular grid. How do you solve such an issue?

**Comment by YoulongXia-NOAA** [comment]
@barlage If my statement is not totally correct, please ask here. We do not need to open another issue as it is the same topic.

**Comment by srherbener** [comment]
For the sake of clarity, the ioda reader needs to have all of the obs in a single file. If you choose an option that produces 6 ioda files, one per tile, these files need to be concatenated into one.

I think the direction we are heading fits well with the above requirement since we're talking about producing one file. Just wanted everyone to keep that requirement in mind as we work toward the solution.

>@tsga @ClaraDraper-NOAA, the today's meeting with Mike and he brought a related question: if you >calculate snow cover fraction from 4km data for a given irregular FV3-grid, some IMS grid points may >be used one more times when worked as a regular grid. How do you solve such an issue?

Do you mean that lat,lon combinations can repeat? If so, and these are temporally separated, then IODA/JEDI will be fine with this. The idea is to have unique location values where a location value is a tuple of either (lat,lon,datetime) or (lat,lon,height,datetime). "height" refers to the many choices for a vertical coordinate.

**Comment by tsga** [comment]
> @tsga @ClaraDraper-NOAA, the today's meeting with Mike and he brought a related question: if you calculate snow cover fraction from 4km data for a given irregular FV3-grid, some IMS grid points may be used one more times when worked as a regular grid. How do you solve such an issue?

Some IMS grid cell can span two FV3 grid cells. Then it 'contributes' to the fractional snow cover area calculation for both grids. We can weigh each contribution by distance to the center of the FV3 grid but (for now at least) just assume equal weights.

**Comment by YoulongXia-NOAA** [comment]
@tsga Okay, understood. From science viewpoint, we can make further investigation. From the engineering viewpoint of our ioda converter,  this should be fine with me.

**Comment by ClaraDraper-NOAA** [comment]
@CoryMartin-NOAA  Are you OK with my using a C48 test? We have one already in the fv3-bundle, and I'm worried that C6 is too coarse to exercise everything we'd want to test.

**Comment by ClaraDraper-NOAA** [comment]
Otherwise, to summarise: I will change the pre-processed file (that will be used as input into the IODA converter) to be a single file which will exclude no data values, and will include the lat & lon of each observation point. I need to think about this some more, but I think I'd also like to include a land fraction for each observation.

**Comment by YoulongXia-NOAA** [comment]
If you use one netcdf file, either C48 0r C96 should be fine as 48x48 or
96x96 size should be fine.
================================================================
Youlong Xia, Ph.D
I. M. Systems Group at EMC/NCEP
5830 University Research Court
College Park, MD 20740
Phone: 301-683-3696
=================================================================

**Comment by CoryMartin-NOAA** [comment]
I agree with @YoulongXia-NOAA, @ClaraDraper-NOAA , as long as it is one tile, or surface only, C48 should be fine. The important part is making sure the unit test 1) runs quickly and 2) the input data are small for easy download and storage.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA Examples of our pre-processed IMS files (which will be the input into IODA converter) are here:

/scratch2/BMC/gsienkf/Clara.Draper/DA_test_cases/snow/fIMS

Note - these are still one file per tile, but you can see the format. We will change our pre-processing to be a single file and to only include locations with data.

**Comment by ClaraDraper-NOAA** [comment]
@jiaruidong2017 will get started on doing this this week.

**Comment by srherbener** [comment]
@YoulongXia-NOAA what's the status of this issue? Please close if it has been resolved. Thanks!

**Comment by YoulongXia-NOAA** [comment]
Yes, I closed it @srherbener
