### ISSUE TITLE
Verify Sensor and Solar Angle Formulas Used in the GOES-16/17 Converter

### ISSUE THREAD

**Issue by ericlingerfelt** [JCSDA-internal/ioda-converters#625]
## Description

This issue addresses the need to verify the formulas used in the GOES-16/17 IODA converter for sensor and solar angles and whether change to the code are required. 

## Acceptance Criteria (Definition of Done)

This issue is complete when the formulas have been verified as the correct ones used for sensor angles.

**Comment by gthompsnJCSDA** [comment]
Since I just comment on the PR#617, I think it is worth commenting here.  What I believe would greatly help is all issues related to converting GOES files is just some plots of the various outputs.  I really think we need to verify that it all looks good visually.

I would really suggest a few channels (truthfully better if all 16) at a few resolutions plus the various MetaData variables.  Perhaps it could be done at 2 times of day (one to ensure sun is up like 18z and another during night hours) and using pretty recent data because we can always cross-check against the various real-time web sites showing these data.

My 2 cents.
