### ISSUE TITLE
create IODA2 converter for concatenated raob BUFR data from LDM server

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#722]
## Description
create an ecCodes based IODA2 converter for raob BUFR files from an LDM server

## Requirements
this requires raob BUFR data and the ecCodes library and the python ecCodes interface

## Acceptance Criteria (Definition of Done)
successful production of IODA2 input file 

## Dependencies
ecCodes must be an option as well as the associated python interface

**Comment by srherbener** [comment]
I've got the concatenation working for multiple messages now. I doubled the ctest data by cat'ing the file with the single bufr message with itself.

The ctest passes, which has a perfect match up between the two messages in the test input file (since they are copies). I coded the concatenator to extend a variable that is missing from the new message with missing values. This function hasn't been tested yet.

I haven't tested with the full file yet. I'll do that next. I just wanted to get the to you so you can try it out.

After the full file, I'll work on reading multiple files.

**Comment by srherbener** [comment]
The converter that is checked into github works on the 2020 Dec 15 file: `2020121500.sonde.BUFR`. This was the file that the eccodes bufr_count program didn't like.

I'm working on processing a list of files in one call to the python script.

**Comment by srherbener** [comment]
I've pushed a commit to github that has the multiple input file processing working. I added a ctest for this where the '-i' argument just lists the WMO bufr file twice.

The 'i' option will accept a space separated list of one or more input bufr files. This should allow you to use the shell file globbing mechanism (eg `-i *.sonde.BUFR`).
