### ISSUE TITLE
SMAP 9km IODA converter should not depend on directory structure

### ISSUE THREAD

**Issue by zcstanley** [JCSDA-internal/ioda-converters#808]
## Description
The SMAP 9km IODA converter handling of date and time currently depend on the directory structure. More specifically, it depends on the number of '\_' symbols in the path where SMAP data is stored. Lines 107-109 in smap9km_ssm2ioda.py  read the file name and split by '_' to find the part of the file name where the information about date and time are stored.

107         str_split = self.filename.split("_")
108         str_datetime = str_split[7]
109         my_datetime = datetime.strptime(str_datetime, "%Y%m%dT%H%M%S")

This does not work for the following path because the path has '_' symbols in it:
filename:
/scratch2/BMC/gsienkf/Zofia.Stanley/projects/smap_qc/my_Data/SMAP_L2_SM_2016/SMAP_L2_SM_P_E_04892_A_20160101T005308_R17000_001.h5

filename split by '_':
['/scratch2/BMC/gsienkf/Zofia.Stanley/projects/smap', 'qc/my', 'Data/SMAP', 'L2', 'SM', '2016/SMAP', 'L2', 'SM', 'P', 'E', '04892', 'A', '20160101T005308', 'R17000', '001.h5']

## Requirements

Converter should not depend on the path. Ideally the date and time would be read in from SMAP metadata, but I have looked briefly and did not find this in the SMAP data files. 

## Acceptance Criteria (Definition of Done)
SMAP 9km IODA converter should not depend on the path. 

## Dependencies
No dependencies.

@YoulongXia-NOAA @srherbener @ClaraDraper-NOAA

**Comment by YoulongXia-NOAA** [comment]
@zcstanley, this is the reason why I cut datetime from file name  and also keep the original long file name as I cannot find where I can input from data file. If you have any idea to read datetime from h5 file, please let me know so that I can modify it.

**Comment by zcstanley** [comment]
@YoulongXia-NOAA I haven't been able to find the date/time in metadata either. You probably saw the same thing I did, that the h5 files have attribute names for the date/time, but these attributes are empty. I just thought I would check in with you to make sure we both found the same thing.

**Comment by YoulongXia-NOAA** [comment]
Yes, we saw the same thing @zcstanley. We need to think about and discuss it in the future.

**Comment by ClaraDraper-NOAA** [comment]
@zcstanley If we absolutely have to take the date from the filename, perhaps you could code it to count back from the end of the filename (or use some other method that does not make assumptions about the directory structure). 

Is there an observation time variable that we could use?

**Comment by ClaraDraper-NOAA** [comment]
@zcstanley Thanks for figuring this out, I would have been surprised if there weren't at least times for the obs themselves. I can't quite follow their terminology  - is there a single value of rangeBeginningDateTime for each file? If so, I think this is what we want.

**Comment by zcstanley** [comment]
@ClaraDraper-NOAA Yes there is a single value of rangeBeginningDateTime. Sounds good, thanks.

**Comment by YoulongXia-NOAA** [comment]
Zofia suggests to add two variables for bias-correction:

ncd.groups['Soil_Moisture_Retrieval_Data'].variables['EASE_row_index']
ncd.groups['Soil_Moisture_Retrieval_Data'].variables['EASE_column_index']

I have added to make a test.

**Comment by YoulongXia-NOAA** [comment]
Avoid to get datetime from the filename, I used the ncd.groups['Soil_Moisture_Retrieval_Data'].variables['tb_time_seconds'] and the reference time since 11:58:55.816 on January 1, 2000 UTC. As new ioda converter upgrade will use dateTime (the seconds since 1970-01-01), this will directly use the addition seconds calculate from reference time and 'tb_time_seconds @zcstanley @ClaraDraper-NOAA. I will create a PR soon via linking this issue.

**Comment by YoulongXia-NOAA** [comment]
@zcstanley, I polish this issue a bit and it looks more formal.  Thank you for finding this problem and creating such an issue.

**Comment by barlage** [comment]
On second thought you already know the number of seconds between the reference times so you could just add that value to what's in the hdf file.

**Comment by YoulongXia-NOAA** [comment]
> h5dump -m '%.3f' -d /Soil_Moisture_Retrieval_Data/tb_time_seconds

 h5dump -m '%.3f' -d /Soil_Moisture_Retrieval_Data/tb_time_seconds SMAP_L2_SM_P_E_36365_D_20211122T013945_R18240_001.h5 to get the first value is (0): 690817334.931

timestamp (s)     946727935 (T1)                    946728000 (T2)        T1+690817335              T2+ 690817335           
UTC                    20000101T11:58:55       20000101T12:00:00        20211122T01:41:09         20211122T01:42:15

Use h5dump -m '%.3f' -d /Soil_Moisture_Retrieval_Data/tb_time_utc SMAP_L2_SM_P_E_36365_D_20211122T013945_R18240_001.h5 to check, the first value is (0): "2021-11-22T01:42:14.931Z". Yes, you are correct @barlage. I will used  946728000  in my python code. @zcstanley, your guess is correct as the value is  690817334.931 rather than 690817000 (h5dump shows only (0): 6.90817e+08). Now I think dateTime is clear.

**Comment by YoulongXia-NOAA** [comment]
> On second thought you already know the number of seconds between the reference times so you could just add that value to what's in the hdf file.

Yes, I used this method as it is simple.
