### ISSUE TITLE
Check how ADPUPA/prepbufr processing deals with the missing Minute, 'MINU', from ADPUPA/bufr

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#945]
## Description

- There are three time-related mnemonics in ADPUPA/prepbufr named: 
DHR (in HOUR) - OBSERVATION TIME MINUS CYCLE TIME 
RPT (in HOUR) - REPORTED OBSERVATION TIME
HRDR (in HOUR) - PROFILE LVL TIME-CYCLE (FOR RAOB/PIBAL, BASED ON B DFT) 

- The prepbufr processing converts the time information to 'DHR' (the difference in HOUR to the analysis time). 

- BUFR mnemonics - "MINU" is not present in some of the ADPUPA subsets like NC002001, NC002002, etc.

- Here, I will check how prepbufr deals with the missing Minute.

## Requirements

- There is no requirement.

## Acceptance Criteria (Definition of Done)

- A similar value of Time/Datetime from BUFR/prepbufr. 

## Dependencies

- There are no dependencies.

**Comment by PraveenKumar-NOAA** [comment]
Values of DHR, RPT, and HRDR (in Hours) extracted from a netcdf file: 

   DHR (nlocs)= 0, 0, 0, 0, -2, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.5, -0.5, -0.5, -0.5, 0.5, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 1,
      1, 0, 0, 0.5, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.5, -0.5, 0, 0, 0,0, -0.5, -0.5, -0.5, -0.5, 0, 0, -0.5, -0.5, 0, 0, 0, 0, 0, 0, 0, 0,
     -0.5, -0.5, 0, 0, -0.5, -0.5, 0, 0, 0, 0, 0, 0, -0.5, -0.5, 0, 0, -0.5,-0.5, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -0.5, -0.5, 0, 0, 0, 0, -0.5,
     -0.5, -0.5, -0.5, 0, 0, 0, 0, 0, 0, 0, 0, -0.5, -0.5, 0, 0, -0.5, -0.5,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.5, -0.5, 0, 0, 0, 0, 0, 0, 
     0 ;


   RPT (Location)= 12, 12, 12, 12, 10, 10, 12, 12, 11, 11, 11, 11,12, 12, 12, 12, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
      12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 10, 10, 12, 12, 12, 12,12, 12, 12, 12, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
      12,12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 12, 12, 12, 12, 12, 12,12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 12, 12, 12, 12, 11, 
      11,11, 11, 12, 12, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 12, 12,11, 11, 12, 12, 12, 12, 12, 12, 11, 11, 12, 12, 11, 11, 12, 12, 12, 
      12,12, 12, 12, 12, 11, 11, 11, 11, 12, 12, 12, 12, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 12, 12, 11, 11, 12, 12, 12, 12, 12, 
      12,11, 11, 12, 12, 12, 12, 12, 12, 11, 11, 12, 12, 12, 12, 12, 12, 12 ;


HRDR (nlocs_prepbufrDataLvlCat) = -0.93, -0.93, -0.92957, -0.92914, -0.92784, -0.92565, -0.91672, -0.91017, -0.90092, 
      -0.89149, -0.87456, -0.80042,-0.79579, -0.79394, -0.7687, -0.67949, -0.65989, -0.576, -0.52876,
      -0.50161, -0.49728, -0.4907, -0.47378, -0.46915, -0.439, -0.41211,-0.33711, -0.2913, -0.24322, -0.21155, -0.16059, 
      -0.11322, -0.00044,0.00455, 0.10678, 0.10873, 0.16175, 0.27567, 0.41733, 0.67956, 0.71706,................

Both, DHR and HRDR, have positive and negative values, while RPT has only positive values. A negative value for time? Mnemonic RPT looks more reasonable for the time in adpupa prepbufr data.

**Comment by gthompsnJCSDA** [comment]
If there is seriously no other full date info embedded inside the bufr, that is pretty non-sensical.  @PraveenKumar-NOAA  Could you point me to a file in the ```test/testinput``` area of either UFO or IODA where I can try searching as well.  Otherwise, a solution eluded to by @emilyhcliu  will have to be undertaken where we have the "exports" section of the yaml specifically give an optional ```referenceTime``` variable that is already formatted as we expect for ISO-9601 like our ```dateTime``` variable.  In other words, in the yaml under exports, we could do something like...

```
        variables:
          timestamp:
            datetime:
              offset: "*/HRDR"
              referenceTime: "2019-11-29T12:00:00Z"
```

Then we simply multiple HRDR values times 3600 (seconds in an hour) and add that result to referenceTime.  The trouble I see possible is that what happens when HRDR is present in some records but not in others?  Are we already certain that a single group is processed one at a time - in other words is the HRDR variable only found in radiosonde data whereas DHR is found in other data types?

If we can trustfully use the idea of the yaml variable for ```offset``` and ```referenceTime``` then it should be somewhat trivial to modify code for timestamp to give the output of ```dateTime```.

**Comment by srherbener** [comment]
DHR, RPT and HRDR all seem to be expressed as an offset in hours from a given reference point. So negative values are okay if this is correct.

DHR and RPT seem to be the same information with their difference being due to the use of a different reference time.

HRDR values don't seem to correspond to either DHR or RPT, so I'm guessing that HRDR are perhaps refinements to more accurately represent drift. That is, HRDR adds in finer resolution of hours to the values in DHR, RPT.

If I've got that right, then I think the algorithm might be something like:
- Ascertain what the proper reference points are for both DHR, RPT
- Assign a precedence for the case where you have both DHR and RPT values.
- Assign zero for HRDR if not present
- Absolute datetime = reference + `DHR or RPT` + HRDR

All of this of course is speculation, and needs to be verified.

We also have the issue that @gthompsnJCSDA mentioned of how to figure out the reference points. Perhaps those are in the BUFR file somewhere (which would be great).

**Comment by PraveenKumar-NOAA** [comment]
@gthompsnJCSDA thank you, I will try out your suggested solution. Also, I need to check if HRDR/DHR found in other datasets.  

Please look at the following file in the ioda-converters for adpupa prepbufr:  https://github.com/JCSDA-internal/ioda-converters/blob/develop/test/testinput/bufr_ncep_prepbufr_adpupa.yaml.

**Comment by PraveenKumar-NOAA** [comment]
@srherbener thank you.

**Comment by PraveenKumar-NOAA** [comment]
@gthompsnJCSDA @srherbener I created a test yaml as suggested by Greg, but it failed to work with the bufr2ioda.x. 

**YAML**
observations:
  - obs space:
      name: bufr

      obsdatain: "/scratch1/NCEPDEV/da/Praveen.Kumar/JEDI/IODA_CONVR_ADPUPA_PB_2020110112/testinput/gdas.t12z.adpupa.prepbufr"

      exports:
        group_by_variable: prepbufrDataLvlCategory
        variables:
          timestamp:
            datetime:
              offset: "*/HRDR"
              referenceTime: "2019-11-29T12:00:00Z"

          # MetaData        
          obsTimeMinusCycleTime:
            query: "*/DHR"
          prepbufrDataLvlCategory:
            query: "*/PRSLEVEL/CAT"
          longitude:
            query: "*/PRSLEVEL/DRFTINFO/XDR"
          latitude:
            query: "*/PRSLEVEL/DRFTINFO/YDR"
          timeCycleProfileLevel:
            query: "*/PRSLEVEL/DRFTINFO/HRDR"
            
          # ObsValue
          pressure:
            query: "*/PRSLEVEL/P___INFO/P__EVENT/POB"
            transforms:
              - scale: 100
            
    ioda:
      backend: netcdf 
      obsdataout: "/scratch1/NCEPDEV/da/Praveen.Kumar/JEDI/IODA_CONVR_ADPUPA_PB_2020110112/testoutput/test_adpupa_prepbufr.nc"

      dimensions:
        - name: PressureEvent
          path: "*/PRSLEVEL/P___INFO/P__EVENT"

      variables:
        # MetaData
        - name: "MetaData/dateTime"
          coordinates: "longitude latitude"
          source: variables/timestamp
          longName: "Datetime"
          units: "seconds since 1970-01-01T00:00:00Z"

        # MetaData
        - name: "MetaData/obsTimeMinusCycleTime"
          coordinates: "longitude latitude"
          source: variables/obsTimeMinusCycleTime
          longName: "Observation Time Minus Cycle Time"
          units: "Hour"

        - name: "MetaData/prepbufrDataLvlCategory"
          coordinates: "longitude latitude"
          source: variables/prepbufrDataLvlCategory
          longName: "Prepbufr Data Level Category"

        - name: "MetaData/longitude"
          coordinates: "longitude latitude"
          source: variables/longitude
          longName: "Longitude"
          units: "degree_east"
          range: [0, 360]

        - name: "MetaData/latitude"
          coordinates: "longitude latitude"
          source: variables/latitude
          longName: "Latitude"
          units: "degree_north"
          range: [-90, 90]
         
        - name: "MetaData/timeCycleProfileLevel"
          coordinates: "longitude latitude"
          source: variables/timeCycleProfileLevel
          longName: "Time Cycle Profile Level"
          units: "Hour"
 
        # ObsValue
        - name: "ObsValue/pressure"
          coordinates: "longitude latitude"
          source: variables/pressure
          longName: "Pressure"
          units: "Pa"

**bufr2ioda.x output**
PRE-MAIN-ERROR Exception: ConfigurationNotFound: [year]
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted

I think it is still looking for the timestamp bufr mnemonics.

**Comment by PraveenKumar-NOAA** [comment]
@srherbener ok, thank you.

**Comment by gthompsnJCSDA** [comment]
For progress, this issue is being worked on via ```feature/prepbufr_timestamp```

**Comment by gthompsnJCSDA** [comment]
@PraveenKumar-NOAA   There is a serious new wrinkle in this mess.  The HRDR variable is TWO-dimensional, not one-dimensional.  Since it comes with some sonde data, the first dimension is for location and the second is for level as the sonde ascends.  This completely STINKS.  We have to create the new destination variable as either a 1D or 2D variable to be safe and re-work the logic where the code is checking for more than 1D variable.  So it is not ready yet.  I will need to consult with @rmclaren to get his help as this is harder than I was hoping since my knowledge of setting up an array as either 1D or 2D is insufficient.

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA thank you for the update. In that case, I think it would be better to use DHR which is 1D and sufficient for the IODA need.


I do not believe that will suffice because then you have a single time for each sounding location, not a series of times as the balloons ascend.  So we need to solve this correctly with ```HRDR```.

**Comment by PraveenKumar-NOAA** [comment]
@gthompsnJCSDA I spoke with @rmclaren and created a new issue (#1088) for him to deal with the 2D variable(s).
