### ISSUE TITLE
Indicate an index in the query string to reduce multi-dimensional arrays to 1-D

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#967]
## Description
It seems when the bufr2ioda code sees a sequence with brackets, it will make a dimension of it, whether or not there are multiple replications. For my results, there's lots of length of 1 dimensions. For example, for my aircraft bufr, the dimensions look like this:

netcdf aircraft_prepbufr_select_thinned {
dimensions:
        CloudSequence = 1 ;
        HeightEvent = 1 ;
        HumidityEvent = 1 ;
        Location = 13664 ;
        PresentWeatherSequence = 1 ;
        PressureEvent = 1 ;
        TemperatureEvent = 1 ;
        WindEvent = 1 ;

We were wondering, is there a way to flatten the data into a 1-D array when the non-Location dimension length =1. For example, since WindEvent =1 in the case above, instead of having a variable's dimensions be (Location, WindEvent), it could be flattened into (Location).

Having a way of indicating an index (or set of indices) in the query string which would let you do this. Right now there is no way to do this. Repeated things (or things where there is a potential for a repeat will always add an extra dimension

## Requirements

Any fix would reduce the number of dimensions and "flatten" the data to a 1-D for any multi-dimensional array where the length of one of the dimensions is 1. 

## Acceptance Criteria (Definition of Done)
Files and yamls affected would need to be edited and tested with the updates.

## Dependencies
None.

**Comment by rmclaren** [comment]
Implementing a way to specify a "column" filter as part of a query string. So for example you can do something like this `*/BRIT{1, 3-5}/TMBR`. '{1, 3-5}' is a filter and lets you specify the "columns" (really repeats of the sequence BRIT) you want to keep in the output data. If you do something like this `*/BRIT{2}/TMBR` it means we can drop the extra dimension associated with the BRIT sequence since we are only keeping 1 repeats worth of information.
