### ISSUE TITLE
"ACID" mnemonic does not work

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#993]
I am trying to add the mnemonic "ACID" to the AIRCFT Prepbufr yaml/output. When I put the mnemonic in, the yaml doesn't like it. I believe the reason is due to this: the input file actually contains two dataypes in it (AIRCFT and AIRCAR). With the exception of one mnemonic (ACID), the two sequences are exactly the same. All other variables are fine.

From the bufr table:
```
| AIRCAR   | HEADR  ACID  {PRSLEVLA}  <LATCORSQ>  <LONCORSQ>                 
| AIRCFT   | HEADR  <ACID_SEQ>  {PRSLEVLA}  <LATCORSQ>  <LONCORSQ> 
```
where
```
| ACID_SEQ | ACID  
```

The queries for ACID, according to print_queries.x are: ``` AIRCFT/ACID_SEQ/ACID``` and  ```AIRCAR/ACID``` and the query for prepbufrDataLevelCategory is  ``` */PRSLEVLA/CAT  ```
Regardless of what combination I use for my query, I get the failure as seen at the bottom of this message. Some individual ones do work, however...

The following queries do NOT work:
```
[*/ACID, */ACID_SEQ/ACID]
AIRCFT/ACID_SEQ/ACID
*/ACID_SEQ/ACID
```

But the following queries DO work:
```
*/ACID
AIRCAR/ACID
```

Initially we used prepbufrDataLevelCategory as our group_by field. I'm thinking that this is the issue has to do with ACID having two different queries. What do you suggest we do in this situation? When I try to group_by: aircraftFlightNumber (ACID), I get a SegFault.

The working directory is here:
/scratch1/NCEPDEV/da/Nicholas.Esposito/JEDI/AIRCFT_PB_CONV_2020110112/

The test yaml is:
acid_problem.yaml

The input file is:
testinput/gdas.t12z.acft_profiles.prepbufr

The queries:
testinput/gdas.t12z.prepbufr.acft_profiles.queries

The bufr table is:
testinput/acft_profile_table

The error I get when I run acid_problem.yaml is:
```
[Nicholas.Esposito@hfe02 AIRCFT_PB_CONV_2020110112]$ ../bufr2ioda.x acid_problem.yaml
Start
Executing Queries
Building Bufr Data
Exporting Data
Finished [0.023s]
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: ../../src/H5D.c line 280 in H5Dopen2(): name parameter cannot be an empty string
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'std::_Nested_exception<ioda::Exception>'
  what():       Reason: An exception occurred inside ioda while opening a variable.
        name:
        source_column:  0
        source_filename:        /scratch1/NCEPDEV/da/Nicholas.Esposito/JEDI/ioda-bundle_20220630/ioda-bundle/ioda/src/engines/ioda/src/ioda/Has_Variables.cpp
        source_function:        virtual ioda::Variable ioda::detail::Has_Variables_Base::open(const string&) const
        source_line:    108

Aborted
```

_Originally posted by @nicholasesposito in https://github.com/JCSDA-internal/ioda-converters/issues/905#issuecomment-1171759802_

**Comment by nicholasesposito** [comment]
New update:
The original file (acid_problem.yaml) works. I made a second file (acid2.yaml) which does not. The main difference is the acid_problem file uses a full acft_profiles prepbufr file (4.3M) and the acid2 uses a smaller file (193K).

/scratch1/NCEPDEV/da/Nicholas.Esposito/JEDI/AIRCFT_PB_CONV_2020110112/acid_problem.yaml
/scratch1/NCEPDEV/da/Nicholas.Esposito/JEDI/AIRCFT_PB_CONV_2020110112/acid2.yaml

**Comment by YoulongXia-NOAA** [comment]
@Nick, @Emily, we actually need to use the actual gdas data for a test.  I also tested aircft prebufr rather than profile, the same problem exists.  What I did is sunsetting the prebufr data into aircft, aircar, etc. There may be some issues there and need to be fixed.

**Comment by rmclaren** [comment]
I made a buig fix lately that might have affected this. Could you please update and try again... Please mark this issue as resolved if its fixed.

**Comment by YoulongXia-NOAA** [comment]
@rmclaren, just re-built ioda-bundle using feature/query_cxx_types, and I tested for aircft profile prepbufr file in /scratch1/NCEPDEV/da/Youlong.Xia/test/bufrCloud/yaml/global, do "../type_bufr2ioda.x bufr_ncep_prepbufr_aircftCloud.yaml"   in/scratch1/NCEPDEV/da/Youlong.Xia/test/bufrCloud/yaml/global. Look the output was produced but not a clean work.
 PRE-MAIN-INFO Start
PRE-MAIN-INFO Executing Queries
PRE-MAIN-INFO Building Bufr Data
PRE-MAIN-INFO Exporting Data
PRE-MAIN-INFO Finished [0.612s]
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: ../../src/H5D.c line 280 in H5Dopen2(): name parameter cannot be an empty string
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Abort

When I used query: "*/ACID_SEQ/ACID".  When I used query: "[*/ACID]". it shows PRE-MAIN-WARNING Warning: Query String [*/ACID] didn't apply to subset AIRCFT.

**Comment by YoulongXia-NOAA** [comment]
@rmclaren, I just output a grep -ACID file ACID_out in /scratch1/NCEPDEV/da/Youlong.Xia/test/bufrCloud/testinput/preBufr for aircft prepbufr file, it shows a mixing with:
 
<ACID_SEQ>     0 REPLICATIONS      and 
001006  ACID                    LXQRFEIQ  ( 8)CCITT IA5                 AIRCRAFT FLIGHT NUMBER
           <ACID_SEQ>     1 REPLICATIONS

May this bring some problem? I am not sure.

**Comment by nicholasesposito** [comment]
@YoulongXia-NOAA  It shouldn't. I just tried it with the different files that I have. I no longer get errors and it appears to me that all the ACID data in the prepbufr files are now in the ioda nc files. Thank you @rmclaren for fixing this!

**Comment by YoulongXia-NOAA** [comment]
@nicholasesposito, could you please help me to test bufr_ncep_prepbufr_aircftCloud.yaml in /scratch1/NCEPDEV/da/Youlong.Xia/test/bufrCloud/yaml/global and see if it passed? You need to make corresponding modification for testinput and testrun directory.

**Comment by nicholasesposito** [comment]
@rmclaren I was able to get mine working ( as well as Youlong) by changing "group_by_variable" to just "group_by" as it used to be. Can you confirm that "group_by" is what it is supposed to be?

**Comment by rmclaren** [comment]
@nicholasesposito I think it might depend on the data file. It still looks like there is an issue to me. I am looking into it.

**Comment by rmclaren** [comment]
Its group_by_variable, but that group by field isn't necessary at all... When you put "group_by" its just getting ignored.

**Comment by rmclaren** [comment]
@nicholasesposito The reason that group by declaration is uneccessary is because is cause the group by field you are using is 1:1 with the trunk (ie root) of the tree (binary repeat only repeats 1 time). Grouping with something that is 1:1 with the trunk if the tree has no effect on the organization of the data. There is a general bug where grouping things that are inside of binary repeats causes problems. This is one of the main issues I will need to solve in a future iteration of the code (may involve some refactoring).

**Comment by YoulongXia-NOAA** [comment]
@rmclaren @nicholasesposito, Yes! when I changed "group_by_variable" to  "group_by", it works now.  If group_by is not needed, can I just removed it @rmclaren?

**Comment by rmclaren** [comment]
Yes, please delete it.

**Comment by YoulongXia-NOAA** [comment]
@nicholasesposito, I can remove the "group_by_variable" for individual aircft yaml file. However, when we work for the whole prepbufr yaml file including ADPSFC, ADPUPA, AIRCFT, AIRCAR, etc, can I remove  the "group_by_variable" it as aircar yaml file also includes it?

**Comment by nicholasesposito** [comment]
@rmclaren I may be confused again. There are other variables that are greater-than-1-bit delayed replications in the sequences, so why don't we need group_by?

**Comment by YoulongXia-NOAA** [comment]
@nicholasesposito, I just got the examples from Emily's directory and start to learn. I am not sure why it was used. You know more than me. If you think that I can remove the "group_by_variable"  for aircar as well, it is great.

**Comment by rmclaren** [comment]
@nicholasesposito What matters is were you put the pivot, where the **group_by_variable** is in relation to the other variables. The path actually matters a lot more than the specific variable (maybe we should have called it group_by_path). Binary paths don't add a dimension so they don't count (look at the output from print_queries). If the path of the dimension is */ or <subset>/ then the operation doesn't do anything. Why? Because everything is already grouped that way (nothing to do). Everything is grouped according to its row location (the very first dimension) by default.

Some examples for different pivots. **STUFF** means anything including other nested repeated sequences. If stuff is a nested repeated thing then it has extra dimensions of its own of coarse, so just think of it as a collection of things (its a box with more junk in it). 

```
*/**STUFF** (or anything else)
^
```
Doesn't do anything. Dims of **STUFF** = [N] (linear array of N things)

```
*/BRITSC/**STUFF**
    ^
```
Everything to the left and including BRITSC is flattened out.

Original Dimensions of **STUFF** = [N, M]
After pivot (applying group by) = [N*M] (2 dimensional **STUFF** turned into 1 dimensional thing).

```
*/ABC/XYZ/**STUFF**
   ^
```
Pivot according to ABC.
Original Dimensions of **STUFF** = [N,M,L]
New dimensions = [N\*M, L] (3d thing turns into 2d thing)

```
*/ABC/XYZ/**STUFF**
       ^
```
Original Dimensions of **STUFF** = [N,M,L]
New Dimension = [N\*M\*L] (**STUFF** got flattened into a 1d thing)


Simple example with some data:

Let's say we have some radiance data in a sequence called BRITSC (some 2d data). Let's say we want to group_by_variable the data by the channel number (same as grouping by the dimensioning path (*/BRITSC). ** This is a stupid example as usually you'd want to group by a position, but just for illustration. **
```
*/BRITSC/TMBR
*/BRITSC/CHNM
    ^
```

Original Data

| | chan1  | chan 2 | chan 3 | chan 4| 
| -------------| ------------- | ------------- | ------------- | ------------- |
| **msg 1** | 124 | 2345  | 1234 | 2345 |
| **msg 2** | 1234 | 4566 | 1234 | 2345 |
| **msg 3** | 1234 | 425  | 1234 | 2345 |
| **msg 4** | 1234 | 3331 | 1234 | 2345 |
| **msg 5** | 1234 | 8628  | 1234 | 2345 |
| **msg 6** | 1234 | 2134 | 1234 | 2345 |

Pivoted Data
| | |
| -------------| ------------- |
| **chan 1** | 124 |
| **chan 2** | 2345 |
| **chan 3** | 1234 |
| **chan 4** | 2345 |
| **chan 1** | 1234 |
| **chan 2** | 4566 |
| **chan 3** | 1234 |
| **chan 4** | 2345 |
| **chan 1** | 1234 |
| ... | ... |

So you've basically pivoted the channels down and they get repeated for each msg. The total number of new rows is now the number of messages * number of channels

**Comment by BenjaminRuston** [comment]
@nicholasesposito this issue is still active correct, moving to icebox but wonder if we shouldn't move this to a new current Epic

**Comment by nicholasesposito** [comment]
Yes it is still active and being worked on. It's already in the enhancements epics so if there's a newer one then maybe we could do that?

**Comment by BenjaminRuston** [comment]
@nicholasesposito yes agree we should maybe think about moving some of the remaining issues to more current epics but will table that for now, until can speak with Emily and Andrew if that sounds like a good idea.

**Comment by nicholasesposito** [comment]
Back from vacation but looking at / working on this now!

**Comment by BenjaminRuston** [comment]
@nicholasesposito and @emilyhcliu is this still active or has been superseded by new issues?
